version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    ignore:
      - dependency-name: "markdown-to-jsx"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "tailwindcss"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
    groups:
      all:
        patterns: [ "*" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    groups:
      all-images:
        patterns: [ "*" ]
    ignore:
      - dependency-name: "node"
        update-types: [ "version-update:semver-major" ]